{
  "openapi": "3.0.0",
  "info": {
    "title": "Documentação da API",
    "description": "Está é uma aplicação para listagem e criação de usuários",
    "version": "1.0.0",
    "contact": {
      "name": "Suporte API",
      "email": "iannrst11@gmail.com"
    }
  },
  "tags": [
    {
      "name": "Users",
      "description": "Gerenciamento de usuário"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Criar um novo usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "Name Example",
                  "email": "example@email.com"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": "a375884a-6600-4570-bc26-3a3f27c0053f",
                      "admin": false,
                      "name": "Name Example",
                      "email": "example@email.com",
                      "created_at": "2022-12-01T14:16:12.806Z",
                      "updated_at": "2022-12-01T14:16:12.806Z"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "User already exists!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "User already exists!"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Retorna todos os usuários.",
        "description": "Somente usuário `admin` pode acessar.",
        "parameters": [
          {
            "in": "header",
            "name": "user_id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "value": [
                      {
                        "id": "a375884a-6600-4570-bc26-3a3f27c0053f",
                        "admin": false,
                        "name": "Name Example",
                        "email": "example@email.com",
                        "created_at": "2022-12-01T14:16:12.806Z",
                        "updated_at": "2022-12-01T14:16:12.806Z"
                      },
                      {
                        "id": "46294910-6a1b-40e0-8a92-f1c27bdd305d",
                        "admin": true,
                        "name": "Name Example 2",
                        "email": "example2@email.com",
                        "created_at": "2022-12-01T10:23:15.516Z",
                        "updated_at": "2022-12-01T16:23:15.516Z"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "400": {
          "description": "Usuário sem permissão ou Usuário não encontrado.",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "error": {
                    "type": "string",
                    "example": "User is not an administrator"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Buscar um usuário especifico pelo ID.",
        "description": "Buscar e retorna um usuário que possua o `id` enviado.",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "description": "ID do usuário que quer buscar.",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": "a375884a-6600-4570-bc26-3a3f27c0053f",
                      "admin": false,
                      "name": "Name Example",
                      "email": "example@email.com",
                      "created_at": "2022-12-01T14:16:12.806Z",
                      "updated_at": "2022-12-01T14:16:12.806Z"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "User not found."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}/admin": {
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Mudar um usuário para admin.",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "description": "ID do usuário que vai virar admin.",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": "a375884a-6600-4570-bc26-3a3f27c0053f",
                      "admin": true,
                      "name": "Name Example",
                      "email": "example@email.com",
                      "created_at": "2022-12-01T14:16:12.806Z",
                      "updated_at": "2022-12-01T14:16:12.806Z"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "User not found."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "admin": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date"
          },
          "updated_at": {
            "type": "string",
            "format": "date"
          }
        }
      }
    }
  }
}